# Generated by Django 3.0.7 on 2020-06-25 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('MOB', 'Mobiliario'), ('TEX', 'Textil'), ('LIB', 'Libros'), ('UTE', 'Utensilios'), ('JUG', 'Juguetes')], max_length=3)),
                ('description', models.TextField(default='')),
                ('years', models.IntegerField()),
                ('pic', models.ImageField(null=True, upload_to='')),
                ('location', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
