# Generated by Django 3.0.7 on 2020-06-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200625_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='appbbc/static/images/no-img.jpg', upload_to='gallery'),
        ),
    ]
