# Generated by Django 3.0.7 on 2020-07-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200714_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/articulos/', upload_to='articulos'),
        ),
    ]
