# Generated by Django 3.0.7 on 2020-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200714_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='appbbc/static/images/', upload_to='articles'),
        ),
    ]
