# Generated by Django 3.0.7 on 2020-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200714_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='articles/no-img.jpg', upload_to='articles/'),
        ),
    ]
