# Generated by Django 3.0.7 on 2020-07-14 13:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200714_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/jvn/Documents/DEV/AppBBC/media'), upload_to=''),
        ),
    ]
