# Generated by Django 3.0.7 on 2020-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200714_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='years',
        ),
        migrations.AddField(
            model_name='product',
            name='functionality',
            field=models.CharField(choices=[('IMP', 'Impecable'), ('NOR', 'Algún deterioro pero no afecta a su funcionalidad'), ('DEF', 'Algún deterioro que sí afecta a su funcionalidad')], default=1, max_length=3, verbose_name='Estado de uso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MOB', 'Mobiliario'), ('TEX', 'Textil'), ('LIB', 'Libros'), ('UTE', 'Utensilios'), ('JUG', 'Juguetes')], max_length=3, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=100, verbose_name='Descripción del artículo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=20, verbose_name='Localidad'),
        ),
    ]
