# Generated by Django 3.0.7 on 2020-07-14 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_auto_20200714_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='functionality',
            field=models.CharField(choices=[('PER', 'Como nuevo y en perfecto estado de uso'), ('NOR', 'Algún deterioro pero no afecta a su funcionalidad'), ('DEF', 'Algún deterioro que afecta ligeramente a su funcionalidad')], max_length=3, verbose_name='Estado de uso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='articles/%Y/%m/%d', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
