# Generated by Django 3.0.7 on 2022-03-22 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0028_auto_20200716_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=100, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='functionality',
            field=models.CharField(blank=True, choices=[('PER', 'Como nuevo y en perfecto estado de uso'), ('NOR', 'Algún deterioro pero no afecta a su funcionalidad'), ('DEF', 'Algún deterioro que afecta ligeramente a su funcionalidad')], max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_location, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_bk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Category', blank=True),
        ),
    ]
