# Generated by Django 3.0.7 on 2022-03-22 22:18

from django.db import migrations
from products.models import Category, Product
from django.utils.text import slugify

def link_categories(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    for prod in Product.objects.all():
        cat, created = Category.objects.get_or_create(
            title=prod.category,
            slug=slugify(prod.category))
        prod.category_bk = cat
        prod.save()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20220322_2215'),
    ]

    operations = [
        migrations.RunPython(link_categories)
    ]
