# Generated by Django 3.0.7 on 2022-03-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_transfer_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
